name: Upload Python Package

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Build source distribution
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Build sdist
      run: pipx run build --sdist
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.3.0
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
